### ISSUE TITLE
Search: UI for twitter suggestions in typeahead

### ISSUE THREAD

**Issue by gakshay** [gakshay/hookhook#11] opened 2015-04-13 04:24 UTC
When a user search for another user in Search Box, we need couple of UI Modifications:
- [x] Search Box needs to be prettier and responsive
- [x] Placeholder text in the Search box needs to be correct
- [x] Search results should look consistent and prettier
- [x] Verified users in search should have verified icon in the search results

**Comment by vikrambahl** [comment] 2015-04-13 14:52
Duplicate of the other issue!

**Comment by gakshay** [comment] 2015-04-15 06:29
@vikrambahl closed the other one..and updated the Description

**Comment by gakshay** [comment] 2015-04-15 14:12
@vikrambahl let us know if you have some time today to complete this story today? @guptapiyush is having a demo tomorrow and this one is the high priority item as of now

**Closed as completed** 2015-04-16 08:33 UTC
Labels: duplicate, High Priority
