### ISSUE TITLE
Important Bugs & Fixes required

### ISSUE THREAD

**Issue by guptapiyush** [gakshay/hookhook#64] opened 2015-07-18 23:06 UTC
- [x] BUG 1 - Two inputs are overlapping currently.

<img width="187" alt="screen shot 2015-07-18 at 3 20 34 pm" src="https://cloud.githubusercontent.com/assets/3889292/8763730/c691bbb8-2d60-11e5-8587-c96cebc07fff.png">
- [x] BUG 2 - Once I add a long message, I can't even respond to "I have met/never met before" because of overlapping.

<img width="199" alt="screen shot 2015-07-18 at 3 20 11 pm" src="https://cloud.githubusercontent.com/assets/3889292/8763736/03a43d46-2d61-11e5-9dfc-c8273a282268.png">
- [x] BUG 3 - The information on 'i' is currently looking weird. I think CSS is the problem here.

<img width="106" alt="screen shot 2015-07-18 at 3 20 22 pm" src="https://cloud.githubusercontent.com/assets/3889292/8763738/0c8f1cf0-2d61-11e5-8fbf-412744182322.png">
- [x] FIX 1 -  Pop up on <img width="16" alt="screen shot 2015-07-18 at 3 27 08 pm" src="https://cloud.githubusercontent.com/assets/3889292/8763745/77a002e8-2d61-11e5-8e4a-6379ad0cdcfd.png"> icon should appear on HOVER.
- [x] FIX 2 - Increase the number of emotions. Yuhuan today shared lots of feedback. One among them was that 'appreciate' and 'inspired' are not too very distinct emotions.

<img width="207" alt="screen shot 2015-07-18 at 3 43 46 pm" src="https://cloud.githubusercontent.com/assets/3889292/8763808/ce539fbc-2d63-11e5-9489-ec7b19585467.png">
- [x] FIX 3 - Each tile must reflect that 'the ability to request a conversation is coming soon'.
  FIX 4 - Label colors and placeholder colors need consistency. Attaching the final tile image

<img width="454" alt="screen shot 2015-07-18 at 4 05 10 pm" src="https://cloud.githubusercontent.com/assets/3889292/8763861/e678586e-2d66-11e5-8a46-c8658d3f43d2.png">

**Comment by gakshay** [comment] 2015-07-20 09:37
Unable to reproduce Bug 1 and Bug 2...

**Comment by sanjusoftware** [comment] 2015-07-21 09:22
bugs #1 and #2 here are only happening on Safari browser it seems and thats not used as much.... closing this for now... we can revisit this later sometimes

maybe adding a new bug just for the Safari fix can be made

**Closed as completed by sanjusoftware** 2015-07-21 09:22 UTC
Labels: High Priority
